dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

ejabberd:
  build: .
  ports:
    - 5222
    - 5269
    - 5280
  environment:
    - XMPP_DOMAIN=example.com
    - ERLANG_NODE=nodename
    - EJABBERD_ADMINS=admin@example.com
    - EJABBERD_USERS=admin@example.com:test321 user@example.com
    - ERLANG_COOKIE=testCluster
    - SKIP_MODULES_UPDATE=true
    - USE_DNS=true
  dns: 172.17.0.2
  domainname: dockercomposecluster_ejabberd.docker
  links:
    - dnsdock
