dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp

ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222
    - 5269
    - 5280
  environment:
    - XMPP_DOMAIN=example.com
    - ERLANG_NODE=ejabberd
    - EJABBERD_ADMIN=admin@example.com
    - EJABBERD_USERS=admin@example.com:test321 user@example.com
    - ERLANG_COOKIE=testCluster
    - EJABBERD_CLUSTER=true
    - USE_DNS=true
  dns: 172.17.42.1
  domainname: ejabberd.docker
#  dns_search: ejabberd.docker
  tty: true
