ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=example.com
    - EJABBERD_ADMIN=admin@example.com
    - EJABBERD_USERS=admin@example.com:password4321
